### ISSUE TITLE
hard to read conditionals in links

### ISSUE THREAD

**Issue by dolanor** [muhwyndhamhp/marknotes#1]
(just a suggestion, based on your nice blog post)
From your [blog post paragraph](https://mwyndham.dev/posts/4#html-logic-sliperry-slopes)

> which is very hard to read but also very hard to debug. As Templates does not throws error codes that is easy to digest. You have to guess a lot of it.

https://github.com/muhwyndhamhp/marknotes/blob/3b516f85276b70d1cf7e44388dbc4ed0c7ebff33/public/components/post_item.html#L3

On this, you could create variables that holds the result of the conditional check and just compose them in your code afterwards.

```diff
- hx-get="/posts?page={{.FormMeta.Page}}&pageSize=10{{if .FormMeta.PublishedOnly}}&status=published{{end}}{{if .FormMeta.SortQuery}}&sortBy={{.FormMeta.SortQuery}}{{end}} {{if .FormMeta.Keyword}}&search={{.FormMeta.Keyword}}{{end}}"
+ {{ if .FormMeta.PublishedOnly }}
+    {{ $published := "&status=published" }}
+ {{ end }}
+ {{if .FormMeta.SortQuery}}
+   {{ $sortBy := "&sortBy={{.FormMeta.SortQuery}}" }}
+ {{ end }}
+ {{if .FormMeta.Keyword}}
+   {{ $search := "&search={{.FormMeta.Keyword}}" }}
+ {{end}}
+ hx-get="/posts?page={{.FormMeta.Page}}&pageSize=10{{ $published }}{{ $sortBy }}{{ $search }}"
```
I'm not 100% sure about this code, but that should be the general idea. I think it's more composable and self explanatory.
More lines, yes, but more readable/graspable.

**Comment by wyndhamharyata** [comment]
Hey, Thank you for reading my blogpost and also thank you for suggesting a solution!!!

Ohhh so we're using template variables here! I have never used template variable just yet. I see I see. Thanks!

I'll test this out and if it works I'll made the change!

**Comment by wyndhamharyata** [comment]
Hi @dolanor. Thanks for this suggestion! though I chooses to go with different solution which you can see here https://github.com/muhwyndhamhp/marknotes/commit/5421a662d7451096dee53a701a62bd108236bed9. I prefer to just move the logic away back to the go code and just pass the final path as a string. 

Thanks anyway!
