### ISSUE TITLE
Preview link?

### ISSUE THREAD

**Issue by bayaderpack** [muhwyndhamhp/marknotes#24]
It looks more than amazing do you maybe have some kind of preview link or live website where you use it.

**Comment by wyndhamharyata** [comment]
Oh hi.

Yes I do use it myself. You can see it here: https://mwyndham.dev/


I might need to edit the Readme later. Thanks!

**Comment by wyndhamharyata** [comment]
Fixed btw! @bayaderpack 

Now the main README.md linked my personal web
